name: openchrom
base: core18

version: '1.4.0.202112230244'
summary: Visualization and Analysis of mass spectrometric and chromatographic data.
description:
  OpenChrom® is an Open Source tool for the analysis and visualization of
  mass spectrometric and chromatographic data developed by Lablicate GmbH.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  openchrom:
    command: bin/openchrom-wrapper

parts:
  openchrom:
    plugin: dump
    source: https://products.lablicate.com/openchrom/1.4.x/openchrom-lablicate_linux.x86_64_1.4.x.tar.gz
    source-checksum: "sha256/e5e7cb90763f0f45f0545fb9b0ec472e4989214a7ebead2f136d759f029eac37"
    build-attributes:
      - no-patchelf
  wrappers:
    plugin: dump
    source: snap/local/wrappers
    organize:
      openchrom: bin/openchrom-wrapper
